### ISSUE TITLE
It is not possible to preview the AI assistant

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-google-ai-search-agent#6]
I tried adding a custom icon etc, but I cannot see the AI assistant in edit mode or in preview?
It should at least be visible in preview mode.

**Comment by sigdestad** [comment]
If assistant is not visible, it will be hard for people to test it.

**Comment by alansemenov** [comment]
It says in README that it only enabled it in LIVE mode: https://github.com/enonic/app-google-ai-search-agent/blame/master/README.md#L5.

We'll fix it to show it in PREVIEW, but I don't see a point in showing it INLINE or EDIT.

**Comment by alansemenov** [comment]
Even when enabled in the preview mode it still won't work out of the box, because admin domain must be authorised in Vertex settings:
  
![image](https://github.com/user-attachments/assets/03b19b20-839d-4ffa-a55f-8b16eae6e618)
